name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Link System Debug Keystore
        run: |
          # Генерируем дефолтный дебаг-ключ, если его еще нет в системе
          mkdir -p ~/.android
          keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          
          # Прописываем путь к НАСТОЯЩЕМУ системному дебаг-ключу и его стандартные пароли
          echo "KEYSTORE_PATH=/home/runner/.android/debug.keystore" > signing.properties
          echo "storeFile=/home/runner/.android/debug.keystore" >> signing.properties
          
          echo "KEYSTORE_PASSWORD=android" >> signing.properties
          echo "storePassword=android" >> signing.properties
          
          echo "KEY_ALIAS=androiddebugkey" >> signing.properties
          echo "keyAlias=androiddebugkey" >> signing.properties
          
          echo "KEY_PASSWORD=android" >> signing.properties
          echo "keyPassword=android" >> signing.properties

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SRPatch-X-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
          
