name: Build Android APK

on:
  workflow_dispatch: # Позволяет запускать сборку вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Create Valid Signing Properties
        run: |
          # Создаем фейковый файл хранилища ключей, чтобы Gradle не ругался на пустой путь
          touch debug.keystore
          
          # Заполняем signing.properties временными данными для успешной компиляции
          echo "KEYSTORE_PATH=../debug.keystore" > signing.properties
          echo "KEYSTORE_PASSWORD=android" >> signing.properties
          echo "KEY_ALIAS=androiddebugkey" >> signing.properties
          echo "KEY_PASSWORD=android" >> signing.properties

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SRPatch-X-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
          
